chore(deps); update lazysizes to forked version

diff --git a/bin/release/prerelease b/bin/release/prerelease
--- a/bin/release/prerelease
+++ b/bin/release/prerelease
@@ -1,29 +1,31 @@
 #!/bin/bash
 
 REQUIRED_TOOLS=(
-  git
-  hugo
-  typos
+	git
+	hugo
+	typos
 )
 
 for TOOL in "${REQUIRED_TOOLS[@]}"; do
-  if ! command -v "${TOOL}" >/dev/null; then
-    echo "${TOOL} is required... "
-    exit 1
-  fi
+	if ! command -v "${TOOL}" >/dev/null; then
+		echo "${TOOL} is required... "
+		exit 1
+	fi
 done
 
 SCRIPTPATH="$(
-   cd "$(dirname "$0")" >/dev/null 2>&1 || exit
-   pwd -P
+	cd "$(dirname "$0")" >/dev/null 2>&1 || exit
+	pwd -P
 )"
 CURPATH="$(pwd -P)"
 
 hugo mod get -u ./...
 hugo mod tidy
+hugo mod vendor
+git add _vendor
 
 git add "${CURPATH}"/go.mod
 FILE="${CURPATH}"/go.sum
 if test -f "$FILE"; then
-    git add go.sum
+	git add go.sum
 fi
