chore: update package and repo file maintenance

diff --git a/modules/debug/bin/release/postrelease b/modules/debug/bin/release/postrelease
--- a/modules/debug/bin/release/postrelease
+++ b/modules/debug/bin/release/postrelease
@@ -1,4 +1,7 @@
-#!/usr/bin/env bash
+#!/bin/bash
+
+# exit when any command fails
+set -e
 
 REQUIRED_TOOLS=(
   git
@@ -11,14 +14,6 @@ for TOOL in "${REQUIRED_TOOLS[@]}"; do
   fi
 done
 
-# adding data directory for new build information
-git add data/dnb/debug/build.json
-git commit --amend --no-edit
-
 # push release to GitHub
-git push --follow-tags origin main
-git push --tags origin main
-
-# create a release on GitHub
-VERSION=$(node -pe 'require("./package.json")["version"]')
-xdg-open https://github.com/davidsneighbour/hugo-debug/releases/tag/v"$VERSION" &>> /dev/null
+git push origin main --follow-tags
+git push origin --tags
diff --git a/modules/feeds/bin/release/postrelease b/modules/feeds/bin/release/postrelease
--- a/modules/feeds/bin/release/postrelease
+++ b/modules/feeds/bin/release/postrelease
@@ -1,4 +1,7 @@
-#!/usr/bin/env bash
+#!/bin/bash
+
+# exit when any command fails
+set -e
 
 REQUIRED_TOOLS=(
   git
@@ -11,8 +14,6 @@ for TOOL in "${REQUIRED_TOOLS[@]}"; do
   fi
 done
 
-git add data/dnb/build/
-git commit --amend --no-edit
-
-git push --follow-tags origin main
-git push --tags
+# push release to GitHub
+git push origin main --follow-tags
+git push origin --tags
diff --git a/modules/feeds/bin/release/prerelease b/modules/feeds/bin/release/prerelease
--- a/modules/feeds/bin/release/prerelease
+++ b/modules/feeds/bin/release/prerelease
@@ -1,8 +1,12 @@
-#!/usr/bin/env bash
+#!/bin/bash
+
+# exit when any command fails
+set -e
 
 REQUIRED_TOOLS=(
   git
   hugo
+  typos
 )
 
 for TOOL in "${REQUIRED_TOOLS[@]}"; do
@@ -12,22 +16,27 @@ for TOOL in "${REQUIRED_TOOLS[@]}"; do
   fi
 done
 
-SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
-
-if test -f "$SCRIPTPATH"/replacements; then
-  while read -ra __; do
-    go mod edit -dropreplace ${__[0]}
-  done < "$SCRIPTPATH"/replacements
+FILE=.env
+if [ -f "$FILE" ]; then
+  echo "exporting .env"
+  set -a # export all variables created next
+  # this routine ranges through a folder of files that we don't explicitly know (@davidsneighbour)
+  # see https://github.com/koalaman/shellcheck/wiki/SC1090
+  # shellcheck source=/dev/null
+  source "${FILE}"
+  set +a # stop exporting
+else
+  echo "no .env file found"
+  exit 0
 fi
+
+CURPATH="$(pwd -P)"
 
 hugo mod get -u ./...
 hugo mod tidy
 
-git add go.mod
-git add go.sum
-
-if test -f "$SCRIPTPATH"/replacements; then
-  while read -ra __; do
-    go mod edit -replace ${__[0]}=${__[1]}
-  done < "$SCRIPTPATH"/replacements
+git add "${CURPATH}"/go.mod
+FILE="${CURPATH}"/go.sum
+if test -f "$FILE"; then
+  git add go.sum
 fi
diff --git a/modules/functions/bin/release/prerelease b/modules/functions/bin/release/prerelease
--- a/modules/functions/bin/release/prerelease
+++ b/modules/functions/bin/release/prerelease
@@ -1,28 +1,42 @@
 #!/bin/bash
 
-# declare path to this script
-SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 || exit ; pwd -P )"
+# exit when any command fails
+set -e
 
-# TODO read component names into array
-# TODO read replacement configuration into array
+REQUIRED_TOOLS=(
+  git
+  hugo
+  typos
+)
 
-# remove replacement scripts
-if test -f "$SCRIPTPATH"/replacements; then
-  while read -ra __; do
-    go mod edit -dropreplace "${__[0]}"
-  done < "$SCRIPTPATH"/replacements
+for TOOL in "${REQUIRED_TOOLS[@]}"; do
+  if ! command -v "${TOOL}" >/dev/null; then
+    echo "${TOOL} is required... "
+    exit 1
+  fi
+done
+
+FILE=.env
+if [ -f "$FILE" ]; then
+  echo "exporting .env"
+  set -a # export all variables created next
+  # this routine ranges through a folder of files that we don't explicitly know (@davidsneighbour)
+  # see https://github.com/koalaman/shellcheck/wiki/SC1090
+  # shellcheck source=/dev/null
+  source "${FILE}"
+  set +a # stop exporting
+else
+  echo "no .env file found"
+  exit 0
 fi
 
-bin/build/prepare-docs
+CURPATH="$(pwd -P)"
 
 hugo mod get -u ./...
 hugo mod tidy
 
-git add go.mod
-git add go.sum
-
-if test -f "$SCRIPTPATH"/replacements; then
-  while read -ra __; do
-    go mod edit -replace "${__[0]}"="${__[1]}"
-  done < "$SCRIPTPATH"/replacements
+git add "${CURPATH}"/go.mod
+FILE="${CURPATH}"/go.sum
+if test -f "$FILE"; then
+  git add go.sum
 fi
diff --git a/modules/head/bin/release/prerelease b/modules/head/bin/release/prerelease
--- a/modules/head/bin/release/prerelease
+++ b/modules/head/bin/release/prerelease
@@ -1,5 +1,7 @@
 #!/bin/bash
-# v20230630.1
+
+# exit when any command fails
+set -e
 
 REQUIRED_TOOLS=(
   git
@@ -28,10 +30,6 @@ else
   exit 0
 fi
 
-SCRIPTPATH="$(
-  cd "$(dirname "$0")" >/dev/null 2>&1 || exit
-  pwd -P
-)"
 CURPATH="$(pwd -P)"
 
 hugo mod get -u ./...
diff --git a/modules/icons/bin/release/postrelease b/modules/icons/bin/release/postrelease
--- a/modules/icons/bin/release/postrelease
+++ b/modules/icons/bin/release/postrelease
@@ -1,3 +1,19 @@
 #!/bin/bash
 
-git push --follow-tags origin main
+# exit when any command fails
+set -e
+
+REQUIRED_TOOLS=(
+  git
+)
+
+for TOOL in "${REQUIRED_TOOLS[@]}"; do
+  if ! command -v "${TOOL}" >/dev/null; then
+    echo "${TOOL} is required... "
+    exit 1
+  fi
+done
+
+# push release to GitHub
+git push origin main --follow-tags
+git push origin --tags
diff --git a/modules/netlification/bin/release/postrelease b/modules/netlification/bin/release/postrelease
--- a/modules/netlification/bin/release/postrelease
+++ b/modules/netlification/bin/release/postrelease
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# exit when any command fails
+set -e
+
 REQUIRED_TOOLS=(
   git
 )
@@ -10,21 +13,6 @@ for TOOL in "${REQUIRED_TOOLS[@]}"; do
     exit 1
   fi
 done
-
-# update version in citation configuration
-FILE=CITATION.cff
-if test -f "$FILE"; then
-  VERSION=$(node -pe 'require("./package.json")["version"]')
-  sed -i "s/^version: .*/version: ${VERSION}/" $FILE
-  DATE=$(date +%F)
-  sed -i "s/date-released: .*/date-released: ${DATE}/" $FILE
-  git add $FILE
-fi
-
-# adding data directory for new build information
-git add data/dnb
-git add README.md
-git commit --signoff --amend --no-edit
 
 # push release to GitHub
 git push origin main --follow-tags
diff --git a/modules/opensearch/bin/release/postrelease b/modules/opensearch/bin/release/postrelease
--- a/modules/opensearch/bin/release/postrelease
+++ b/modules/opensearch/bin/release/postrelease
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# exit when any command fails
+set -e
+
 REQUIRED_TOOLS=(
   git
 )
@@ -10,11 +13,6 @@ for TOOL in "${REQUIRED_TOOLS[@]}"; do
     exit 1
   fi
 done
-
-# adding data directory for new build information
-git add data/dnb
-git add README.md
-git commit --signoff --amend --no-edit
 
 # push release to GitHub
 git push origin main --follow-tags
diff --git a/modules/opensearch/bin/release/prerelease b/modules/opensearch/bin/release/prerelease
--- a/modules/opensearch/bin/release/prerelease
+++ b/modules/opensearch/bin/release/prerelease
@@ -1,8 +1,12 @@
 #!/bin/bash
 
+# exit when any command fails
+set -e
+
 REQUIRED_TOOLS=(
   git
   hugo
+  typos
 )
 
 for TOOL in "${REQUIRED_TOOLS[@]}"; do
@@ -12,15 +16,27 @@ for TOOL in "${REQUIRED_TOOLS[@]}"; do
   fi
 done
 
-CURPATH="$(pwd -P)"
+FILE=.env
+if [ -f "$FILE" ]; then
+  echo "exporting .env"
+  set -a # export all variables created next
+  # this routine ranges through a folder of files that we don't explicitly know (@davidsneighbour)
+  # see https://github.com/koalaman/shellcheck/wiki/SC1090
+  # shellcheck source=/dev/null
+  source "${FILE}"
+  set +a # stop exporting
+else
+  echo "no .env file found"
+  exit 0
+fi
 
-"${CURPATH}"/bin/build/prepare-files
+CURPATH="$(pwd -P)"
 
 hugo mod get -u ./...
 hugo mod tidy
 
 git add "${CURPATH}"/go.mod
 FILE="${CURPATH}"/go.sum
-if test -f "${FILE}"; then
+if test -f "$FILE"; then
   git add go.sum
 fi
diff --git a/modules/pictures/bin/release/postrelease b/modules/pictures/bin/release/postrelease
--- a/modules/pictures/bin/release/postrelease
+++ b/modules/pictures/bin/release/postrelease
@@ -1,16 +1,19 @@
 #!/bin/bash
 
-# update version in citation configuration
-FILE=CITATION.cff
-if test -f "$FILE"; then
-  VERSION=$(node -pe 'require("./package.json")["version"]')
-  sed -i "s/^version: .*/version: ${VERSION}/" $FILE
-  DATE=$(date +%F)
-  sed -i "s/date-released: .*/date-released: ${DATE}/" $FILE
-  git add $FILE
-fi
+# exit when any command fails
+set -e
 
-git add CITATION.cdd
-git commit --signoff --amend --no-edit
+REQUIRED_TOOLS=(
+  git
+)
 
-git push --follow-tags origin main
+for TOOL in "${REQUIRED_TOOLS[@]}"; do
+  if ! command -v "${TOOL}" >/dev/null; then
+    echo "${TOOL} is required... "
+    exit 1
+  fi
+done
+
+# push release to GitHub
+git push origin main --follow-tags
+git push origin --tags
diff --git a/modules/schema/bin/release/postrelease b/modules/schema/bin/release/postrelease
--- a/modules/schema/bin/release/postrelease
+++ b/modules/schema/bin/release/postrelease
@@ -1,8 +1,19 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-# declare path to this script
-SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 || exit ; pwd -P )"
+# exit when any command fails
+set -e
 
-# send all tags to remote
-git push --follow-tags origin main
-git push --tags
+REQUIRED_TOOLS=(
+  git
+)
+
+for TOOL in "${REQUIRED_TOOLS[@]}"; do
+  if ! command -v "${TOOL}" >/dev/null; then
+    echo "${TOOL} is required... "
+    exit 1
+  fi
+done
+
+# push release to GitHub
+git push origin main --follow-tags
+git push origin --tags
