build: update build hooks

diff --git a/modules/auditor/bin/release/postrelease b/modules/auditor/bin/release/postrelease
--- a/modules/auditor/bin/release/postrelease
+++ b/modules/auditor/bin/release/postrelease
@@ -1,7 +1,8 @@
 #!/bin/bash
+# v2023.07.25.2
 
-# exit when any command fails
-set -e
+# exit verbose when any command fails
+set -euxo pipefail
 
 REQUIRED_TOOLS=(
   git
@@ -14,6 +15,49 @@ for TOOL in "${REQUIRED_TOOLS[@]}"; do
   fi
 done
 
+FILE=.env
+if [ -f "$FILE" ]; then
+  echo "exporting .env"
+  set -a # export all variables created next
+  # this routine ranges through a folder of files that we don't explicitly know (@davidsneighbour)
+  # see https://github.com/koalaman/shellcheck/wiki/SC1090
+  # shellcheck source=/dev/null
+  source "${FILE}"
+  set +a # stop exporting
+else
+  echo "no .env file found"
+  exit 1
+fi
+
+VERSION=$(node -pe 'require("./package.json")["version"]')
+
+# update version in citation configuration
+FILE=CITATION.cff
+if test -f "$FILE"; then
+  VERSION=$(node -pe 'require("./package.json")["version"]')
+  sed -i "s/^version: .*/version: ${VERSION}/" $FILE
+  DATE=$(date +%F)
+  sed -i "s/date-released: .*/date-released: ${DATE}/" $FILE
+  git add $FILE
+else
+  echo "no CITATION.cff found"
+  exit 1
+fi
+
+git commit -m "chore(release): update citation configuration" --signoff --no-verify
+
 # push release to GitHub
 git push origin main --follow-tags
 git push origin --tags
+
+# create a release on GitHub
+GITHUB_REPO=https://github.com/${GITHUB_REPOSLUG}
+TAGNAME=${TAGSLUG}v${VERSION}
+URL="$GITHUB_REPO"/"releases/edit/v""$VERSION"
+curl \
+  -X POST \
+  -H "Accept: application/vnd.github+json" \
+  -H "Authorization: token ${GITHUB_SECRET}" \
+  https://api.github.com/repos/"${GITHUB_REPOSLUG}"/releases \
+  -d "{\"tag_name\":\"${TAGNAME}\",\"name\":\"${TAGNAME}\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":true}"
+xdg-open "${URL}" &>>/dev/null
diff --git a/modules/auditor/bin/release/prerelease b/modules/auditor/bin/release/prerelease
--- a/modules/auditor/bin/release/prerelease
+++ b/modules/auditor/bin/release/prerelease
@@ -1,7 +1,8 @@
 #!/bin/bash
+# v2023.07.25.2
 
-# exit when any command fails
-set -e
+# exit verbose when any command fails
+set -euxo pipefail
 
 REQUIRED_TOOLS=(
   git
@@ -27,7 +28,7 @@ if [ -f "$FILE" ]; then
   set +a # stop exporting
 else
   echo "no .env file found"
-  exit 0
+  exit 1
 fi
 
 CURPATH="$(pwd -P)"
